UCM_URL = ""
UCM_PORT = ""

PHONE_1_NAME = ""
PHONE_1_DESCRIPTION = ""
PHONE_LIST_NAMES = [""]
PHONE_LIST_DESCRIPTIONS = [""]
PHONE_LIST_DOESNT_EXIST = [""]
PHONE_DOESNT_EXIST_NAME = ""

DN_1_PATTERN = ""
DN_1_PARTITION = ""
DN_LIST = [("", "")]
DN_BAD_LIST = ["", ("", "")]
DN_DOESNT_EXIST_PATTERN = ""
DN_DOESNT_EXIST_PARTITION = ""
